name: base
channels:
  - conda-forge
  - https://repo.mamba.pm/emscripten-forge
dependencies:
  - cmake
  - pip
  - cxx-compiler
  - python=3.11
  - yarn=3
  - click
  - empack >=3.0.1
  - ninja
  - make
  - nodejs
  - exceptiongroup
  - emscripten_emscripten-wasm32=3.1.45
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq>=3.0,<4.0
  - nlohmann_json=3.11.3
  - pybind11>=2.6.1,<3.0
  - pybind11_json>=0.2.6,<0.3
  - xeus-python-shell>=0.6.3,<0.7
  - debugpy>=1.6.5
  - git
  # xeus  
  - jupyterlite-core
  - empack >=3.3
  - jupyterlab >=4.0
  - requests
  - traitlets
  - pyyaml
  - hatchling
  - hatch-nodejs-version
  - hatch-jupyter-builder