name: Build

on:
  push:
    branches: main
  pull_request:
    branches: "*"
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          npm install
          npm run build
          npm run start
